services:
  traefik:
    image: traefik:v3.0
    container_name: traefik
    restart: unless-stopped
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--log.level=DEBUG"  # Enable debug logging
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"  # Traefik dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - dms-net

  openldap:
    image: bitnami/openldap:2.6
    container_name: openldap
    restart: unless-stopped
    environment:
      LDAP_ADMIN_USERNAME: admin
      LDAP_ADMIN_PASSWORD: ${LDAP_ADMIN_PASSWORD:-adminpassword}
      LDAP_USERS: testuser
      LDAP_PASSWORDS: testpassword
      LDAP_ROOT: dc=dms,dc=local
      BITNAMI_DEBUG: "true"
    volumes:
      - openldap-data:/bitnami/openldap
    ports:
      - "1389:389"  # For external testing
    networks:
      - dms-net
    healthcheck:
      test: ["CMD-SHELL", "ldapwhoami -H ldap://localhost:1389 -D cn=admin,dc=dms,dc=local -w ${LDAP_ADMIN_PASSWORD:-adminpassword} || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 20
      start_period: 120s

  keycloak:
    image: quay.io/keycloak/keycloak:25.0.4
    container_name: keycloak
    restart: unless-stopped
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak?connectTimeout=30&socketTimeout=30&tcpKeepAlive=true
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: ${KEYCLOAK_DB_PASSWORD:-keycloakpassword}
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD:-adminpassword}
      KC_HOSTNAME: keycloak.localhost
      KC_HTTP_ENABLED: "true"
      KC_HTTPS_ENABLED: "true"
      KC_PROXY: edge
      KC_LOG_LEVEL: DEBUG  # Enable debug logging
    depends_on:
      postgres:
        condition: service_healthy
      openldap:
        condition: service_healthy
    volumes:
      - ./keycloak/realm-export.json:/opt/keycloak/data/import/realm.json:ro
    command: start-dev --import-realm
    networks:
      - dms-net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.keycloak.rule=Host(`keycloak.localhost`)"
      - "traefik.http.routers.keycloak.entrypoints=websecure"
      - "traefik.http.routers.keycloak.tls=true"
      - "traefik.http.services.keycloak.loadbalancer.server.port=8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health/ready"]
      interval: 10s
      timeout: 5s
      retries: 15
      start_period: 90s

  jbpm:
    image: jboss/jbpm-server-full:7.61.0.Final
    container_name: jbpm
    restart: unless-stopped
    environment:
      JBPM_DB_DRIVER: postgres
      JBPM_DB_HOST: postgres
      JBPM_DB_PORT: 5432
      JBPM_DB_NAME: jbpm
      JBPM_DB_USER: jbpm
      JBPM_DB_PASSWORD: ${JBPM_DB_PASSWORD:-jbpmpassword}
      KEYCLOAK_URL: ${KEYCLOAK_URL:-https://keycloak.localhost/auth}
      KEYCLOAK_REALM: ${KEYCLOAK_REALM:-dms-realm}
      KEYCLOAK_CLIENT_ID: ${KEYCLOAK_CLIENT_ID:-jbpm-client}
      KEYCLOAK_CLIENT_SECRET: ${KEYCLOAK_CLIENT_SECRET:-clientsecret}
      JBPM_HT_CALLBACK_CLASS: org.jbpm.services.task.identity.KeycloakUserGroupCallbackImpl
      JBPM_HT_CALLBACK_PROPERTIES: keycloak.url=${KEYCLOAK_URL:-https://keycloak.localhost/auth},keycloak.realm=${KEYCLOAK_REALM:-dms-realm},keycloak.clientId=${KEYCLOAK_CLIENT_ID:-jbpm-client},keycloak.clientSecret=${KEYCLOAK_CLIENT_SECRET:-clientsecret}
    depends_on:
      postgres:
        condition: service_healthy
      keycloak:
        condition: service_started
    networks:
      - dms-net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jbpm.rule=Host(`jbpm.localhost`)"
      - "traefik.http.routers.jbpm.entrypoints=websecure"
      - "traefik.http.routers.jbpm.tls=true"
      - "traefik.http.services.jbpm.loadbalancer.server.port=8080"

  mongodb:
    image: mongo:8.0
    container_name: mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD:-mongopassword}
      MONGO_INITDB_DATABASE: bpdata
    volumes:
      - mongodb-data:/data/db
    networks:
      - dms-net

  postgres:
    image: postgres:16
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgrespassword}
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql  # Remove :ro if present
    networks:
      - dms-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  openldap-data:
  openldap-config:
  mongodb-data:
  postgres-data:

networks:
  dms-net:
    driver: bridge
