CREATE USER keycloak WITH PASSWORD '${KEYCLOAK_DB_PASSWORD}';
CREATE DATABASE keycloak;
GRANT ALL PRIVILEGES ON DATABASE keycloak TO keycloak;

CREATE USER jbpm WITH PASSWORD '${JBPM_DB_PASSWORD}';
CREATE DATABASE jbpm;
GRANT ALL PRIVILEGES ON DATABASE jbpm TO jbpm;
